import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div className='text-center'>
        <Script>
            {`alert("this is a dummy contact");`}
        </Script>
      Contact no: 01XXXXXXXXX
    </div>
  )
}

export default contact

export const metadata = {
    title: "Contact Facebook",
    description: "Generated by create next app",
  };