import React from 'react'

const about = () => {
  return (
    <div className='text-center'>
      This is About page
    </div>
  )
}

export default about


export const metadata = {
    title: "About Facebook",
    description: "Generated by create next app",
  };